### ISSUE TITLE
Feature Request: Data-driven brewing recipes

### ISSUE THREAD

**Issue by erisdev** [RomoAlamN/CauldronBrewing#4]
Data-driven recipes would be a great convenience for modpack creators & server owners to customize brewing with a datapack, and mod authors looking to make their mods compatible with yours wouldn't need to bother with optional dependencies. 

A recipe file for the vanilla potion of leaping might look something like this, for example:

```json
{
    "type": "cauldron:brewing",
    "base": "cauldron:awkward", 
    "ingredient": { "item": "minecraft:rabbit_foot" },
    "result": {
        "effect": "minecraft:leaping",
        "amplifier": 0,
        "duration": 3600
    }
}
```

**Comment by RomoAlamN** [comment]
The only thing I would change is 
`"result":{..effect..}`
should be 
```
"results":[
    {..effect..},
    {..effect..}
]
```
That way I can support things like potion of the Turtle master, which has two potion effects. 

One problem with this, however, is that it circumvents the registry which means the potion created cannot be used in any further recipes, a simple solution to this problem is to create a separate place to declare potion types, and then use a reference to the declared type, which would make adding more recipes as easy as a datapack.

So that would become
```
"result":"modid:potion_type"
```
A negative is that it would allow overriding potion effects with others, which could not be avoided due to the way resourcepacks work.

Another possibility is to just get rid of the `PotionType` class altogether, and just pass raw `List<EffectInstance>`s around, which would allow for more flexibility in they potions that can be created, at the expense of making my recipe handling code a little more complicated. 


(This is here to remind me later)

**Comment by RomoAlamN** [comment]
That was a lot of work. I need to add some localizations now, but everything is working properly. I'll probably post the updated version tomorrow.

**Comment by erisdev** [comment]
oh, nice work! thank you
